# Image Operation using OpenCV and Python

In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('flower1.jpg', cv2.IMREAD_COLOR)

#### Display characteristics of image:

In [3]:
print(img.shape)
print(img.size)
print(img.dtype)

(630, 580, 3)
1096200
uint8


#####  we can reference specific pixels, change their color values and dispay them, like : 

In [4]:
px = img[100, 50]
print(px)

#change the color value of pixel to white
img[100, 50] = [255,255,255]
px = img[100, 50]
print(px)

#display image
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[1 1 1]
[255 255 255]


#### we can reference an ROI, or Region of Image as folllowing :

In [5]:
#selecting and displaying all pixels martices
roi = img[100:150,100:150]
print(roi)

#modify the ROI and make it white
img[100:150,100:150] = [255,255,255]
#display image
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [0 0 0]
  [3 3 3]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [0 0 0]
  [3 3 3]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [2 2 2]
  [0 0 0]
  [3 3 3]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [6]:
copy_roi = img[160:360,160:360]
img[0:200,0:200] = copy_roi

cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#saving the output image
cv2.imwrite('copy_pasted.jpg',img)

True